#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "Syncing version..."
bun run sync-version
git add src/version.ts

echo "Formatting..."
bun run format:check

echo "Linting..."
bun run lint

echo "Types..."
bun run check-types

echo "Pre-commit checks passed!"
