#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "Syncing version..."
bun run sync-version
git add src/version.ts

echo "Running Biome (fix)..."
bun run biome:fix

echo "Running Biome (check)..."
bun run biome:check

echo "Types..."
bun run check-types

echo "Pre-commit checks passed!"
